In [2]:
# Basics import
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

#To get rid of warnings
import warnings
warnings.filterwarnings("ignore")

In [3]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [76]:
data = pd.read_excel(r"df_resample.xlsx")

In [84]:
df3=data.copy()
df3.shape

(5368, 8)

In [85]:
X = pd.DataFrame(df3.drop('crop', axis = 1))
y=pd.DataFrame(df3["crop"])

In [86]:
df3.columns

Index(['place', 'soil_pH', 'soil_texture', 'avg_temp', 'sowing_month',
       'season', 'crop', 'crop_type'],
      dtype='object')

In [87]:
X = X.join(pd.get_dummies(X['place']))
X = X.join(pd.get_dummies(X['sowing_month']))
X = X.join(pd.get_dummies(X['soil_texture']))
X = X.join(pd.get_dummies(X['season']))
X = X.join(pd.get_dummies(X['crop_type']))

In [88]:
X = X.drop('place', axis=1)
X = X.drop('season',axis=1)
X = X.drop('soil_texture',axis=1)
X = X.drop('sowing_month',axis=1)
X = X.drop('crop_type',axis=1)

In [82]:
import pickle

In [95]:
X.columns

Index(['soil_pH', 'avg_temp', 'baglung', 'gorkha', 'lamjung', 'syangja',
       'tanahu', 'Sep/oct', 'june/july', 'mar/apr', 'oct/nov',
       ' sandy clay loam', 'clay', 'clay loam', 'loam', 'sandy loam', 'silt',
       'silt loam', 'summer', 'winter', 'cereals', 'other'],
      dtype='object')

In [68]:

# # Encode the target variable
# le_crop = LabelEncoder()
# y['crop'] = le_crop.fit_transform(y['crop'])

# # Encode the categorical features
# categorical_cols = ['season', 'soil_texture', 'sowing_month', 'place', 'crop_type']
# for col in categorical_cols:
#     le = LabelEncoder()
#     X[col] = le.fit_transform(X[col])

# with open('labelencoder.pkl', 'wb') as f:
#     pickle.dump(le, f)

# with open('labelencoderTarget.pkl', 'wb') as f:
#     pickle.dump(le_crop, f)   

In [90]:
y.head 

<bound method NDFrame.head of         crop
0     barley
1     barley
2     barley
3     barley
4     barley
...      ...
5363   wheat
5364   wheat
5365   wheat
5366   wheat
5367   wheat

[5368 rows x 1 columns]>

In [94]:


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)


# Instantiate the Random model
model = RandomForestClassifier(max_depth= 8, max_features= 'auto', min_samples_leaf= 5, min_samples_split= 1)

# Train the model on the training set
model.fit(X_train, y_train)

# Save the model as a pickle file
with open('randomforest.pkl', 'wb') as f:
    pickle.dump(model, f)

In [37]:
df3.columns

Index(['place', 'soil_pH', 'soil_texture', 'avg_temp', 'sowing_month',
       'season', 'crop', 'crop_type'],
      dtype='object')

In [13]:
# le = LabelEncoder()
# y=(pd.DataFrame(le.fit_transform(y)))

In [50]:
X = pd.DataFrame(df3.drop('crop', axis = 1))
y=pd.DataFrame(df3["crop"])

In [73]:
y

crop
0        0
1        0
2        0
3        0
4        0
...    ...
5363    10
5364    10
5365    10
5366    10
5367    10

[5368 rows x 1 columns]

In [72]:
y_df = pd.DataFrame(y)

# Print the mapping of the encoded labels to their original labels
print(dict(zip(range(len(le.classes_)), le.classes_)))

{0: 'cereals', 1: 'other'}


In [42]:
# # Pickle the LabelEncoder
# with open('labelencoder.pkl', 'wb') as f:
#     pickle.dump(le, f)

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [59]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# sc.fit(X_train)
# X_train=pd.DataFrame(sc.transform(X_train),columns=X_train.columns)
# X_test=pd.DataFrame(sc.transform(X_test),columns=X_test.columns)

In [44]:
from sklearn.metrics import confusion_matrix

In [92]:
# Instantiate the Random model
model = RandomForestClassifier(max_depth= 8, max_features= 'auto', min_samples_leaf= 5, min_samples_split= 1)

# Train the model on the training set
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, max_features='auto', min_samples_leaf=5,
                       min_samples_split=1)

In [46]:
# Save the model as a pickle file
with open('randomforest.pkl', 'wb') as f:
    pickle.dump(model, f)

In [47]:
X_train.columns

Index(['place', 'soil_pH', 'soil_texture', 'avg_temp', 'sowing_month',
       'season', 'crop_type'],
      dtype='object')

In [93]:


# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model performance
print("Accuracy score: {:.2f}".format(accuracy_score(y_test, y_pred)))
train_score = model.score(X_train, y_train)
print("Train Score")
print(train_score)
test_score = model.score(X_test, y_test)
print("Test Score")
print(test_score)
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy score: 0.94
Train Score
0.9464368886818817
Test Score
0.9422718808193669
Confusion matrix:
[[ 92   0   0   0   0   0   0   0   0   0   1]
 [  0  93   0   0   0   0   0   0   0  15   0]
 [  0   0  92   0   0   0   0   0   0   0   0]
 [  0   0   0  93   0   0   0   0   0   0   0]
 [  0   0   0   0 102   0   0   0   0   0   0]
 [  0   0   0   0   0 101   0   0   0   0   0]
 [  0   0   0   0   0   0  96   0   2   0   0]
 [  0   0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0  44   0  47   0   0]
 [  0   0   0   0   0   0   0   0   0  88   0]
 [  0   0   0   0   0   0   0   0   0   0 108]]
